// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyatkmqoydfwfolblruu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5YXRrbXFveWRmd2ZvbGJscnV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDAzNDQsImV4cCI6MjA2NDAxNjM0NH0.g0uIIvWhHiqnnspw5nV1YvXHmZFlytlJkcVAcnBeQ6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);